version: '3.8'
services:
  db:
    image: postgres:15
    container_name: todo_postgres
    environment:
      - POSTGRES_USER: todouser
      - POSTGRES_PASSWORD: todopass
      - POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg-isready -U todouser -d tododb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

backend:
  build: ./backend
  container_name: todo_backend
  ports:
    - "8000:8000"
  environment:
    DATABASE_URL: postgresql://todouser:todopass@db:5432/tododb
  depends_on:
    db:
      condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
